In [1]:
import torch 

inputs = torch.tensor(
[
    [0.43, 0.15, 0.89], # your
    [0.55, 0.87, 0.66], # journey
    [0.57, 0.85, 0.64], # starts
    [0.22, 0.58, 0.33], # with
    [0.77, 0.25, 0.10], # one
    [0.05, 0.80, 0.55] # step
]
)

In [ ]:
# Query vector 
query_vector = inputs[2]  # Index 2 = "starts"

print("Query Vector (starts):", query_vector)

Query Vector (starts): tensor([0.5700, 0.8500, 0.6400])


In [ ]:
# Attention scores
attn_scores_2 = torch.zeros(len(inputs))  
for i, x_i in enumerate(inputs):
  print(f"Word {i} vector: {x_i}")
  attn_scores_2[i] = torch.dot(x_i, query_vector)

print("\nAttention Scores:", attn_scores_2)

Word 0 vector: tensor([0.4300, 0.1500, 0.8900])
Word 1 vector: tensor([0.5500, 0.8700, 0.6600])
Word 2 vector: tensor([0.5700, 0.8500, 0.6400])
Word 3 vector: tensor([0.2200, 0.5800, 0.3300])
Word 4 vector: tensor([0.7700, 0.2500, 0.1000])
Word 5 vector: tensor([0.0500, 0.8000, 0.5500])

Attention Scores: tensor([0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605])


In [6]:
# Attention weights = attention scores transformed in probability (softmax)
attn_weights = torch.softmax(attn_scores_2, dim=0)

print("Attention Weights (Softmax):", attn_weights)


Attention Weights (Softmax): tensor([0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565])


In [7]:
# Context vector
context_vector = torch.sum(attn_weights[:, None] * inputs, dim=0)
print("Context Vector:", context_vector)

Context Vector: tensor([0.4431, 0.6496, 0.5671])


In [8]:
# All words

# Création de Q, K et V 
W_Q = torch.randn(3, 3)  # Matrice des Queries
W_K = torch.randn(3, 3)  # Matrice des Keys
W_V = torch.randn(3, 3)  # Matrice des Values

Q = inputs @ W_Q  
K = inputs @ W_K  
V = inputs @ W_V  

# Attention scores
attn_scores = Q @ K.T  

# Attention weights
attn_weights = torch.nn.functional.softmax(attn_scores, dim=1)

# Context vector
context_vector = attn_weights @ V

print("Attention scores:\n", attn_scores)
print("Attention weights(Softmax):\n", attn_weights)
print("Context vector:\n", context_vector)

Attention scores:
 tensor([[ 2.6427,  4.0432,  4.0849,  2.0004,  3.6882,  1.7522],
        [ 1.1121,  3.1939,  3.2997,  1.5280,  4.2758,  0.6275],
        [ 1.1278,  3.1771,  3.2839,  1.5120,  4.2831,  0.6013],
        [ 0.2329,  1.4106,  1.4675,  0.6870,  2.0786,  0.1898],
        [ 1.0943,  1.9823,  2.0776,  0.7994,  3.2089, -0.0389],
        [ 0.1420,  1.7081,  1.7589,  0.9060,  2.1774,  0.4759]])
Attention weights(Softmax):
 tensor([[0.0765, 0.3104, 0.3237, 0.0403, 0.2177, 0.0314],
        [0.0229, 0.1834, 0.2039, 0.0347, 0.5411, 0.0141],
        [0.0233, 0.1809, 0.2013, 0.0342, 0.5466, 0.0138],
        [0.0604, 0.1962, 0.2077, 0.0952, 0.3827, 0.0579],
        [0.0647, 0.1572, 0.1730, 0.0482, 0.5361, 0.0208],
        [0.0454, 0.2174, 0.2287, 0.0975, 0.3476, 0.0634]])
Context vector:
 tensor([[ 0.5115,  0.0890, -0.6006],
        [ 0.5043,  0.1628, -0.4568],
        [ 0.5043,  0.1634, -0.4538],
        [ 0.4780,  0.1176, -0.5031],
        [ 0.4983,  0.1410, -0.4333],
        [ 0.4769

In [9]:
import torch.nn as nn

# Matrixes 
Wq = nn.Parameter(torch.randn(3, 3))  
Wk = nn.Parameter(torch.randn(3, 3))  
Wv = nn.Parameter(torch.randn(3, 3))  

# Inputs[2] - starts 
input_for_starts = inputs[2] 

# Q, K, V
query_for_starts = torch.matmul(input_for_starts, Wq)  
key_for_starts = torch.matmul(input_for_starts, Wk)    
value_for_starts = torch.matmul(input_for_starts, Wv)  

print("Query 'starts':\n", query_for_starts)
print("Key 'starts':\n", key_for_starts)
print("Value 'starts':\n", value_for_starts)

Query 'starts':
 tensor([-1.9908, -0.8355,  0.3953], grad_fn=<SqueezeBackward4>)
Key 'starts':
 tensor([ 1.5079, -0.2364,  0.5598], grad_fn=<SqueezeBackward4>)
Value 'starts':
 tensor([1.0573, 2.3881, 3.7660], grad_fn=<SqueezeBackward4>)


In [10]:
# Matrixes 
Wq = nn.Parameter(torch.randn(3, 3))  
Wk = nn.Parameter(torch.randn(3, 3))  
Wv = nn.Parameter(torch.randn(3, 3))  

# Inputs[1] - journey
input_for_journey = inputs[1] 

# Q, K, V
query_for_journey = torch.matmul(input_for_journey, Wq)  
key_for_journey = torch.matmul(input_for_journey, Wk)    
value_for_journey = torch.matmul(input_for_journey, Wv)  

print("Query 'journey':\n", query_for_journey)
print("Key 'journey':\n", key_for_journey)
print("Value 'journey':\n", value_for_journey)

Query 'journey':
 tensor([-0.2992, -2.3014,  1.2407], grad_fn=<SqueezeBackward4>)
Key 'journey':
 tensor([ 1.1865, -1.3654,  1.7758], grad_fn=<SqueezeBackward4>)
Value 'journey':
 tensor([1.0650, 2.5115, 1.6445], grad_fn=<SqueezeBackward4>)


In [11]:
# Attention Score inputs[1][1]
attn_score_11 = torch.dot(query_for_journey, key_for_journey)
print("Attention score ω11:\n", attn_score_11)

Attention score ω11:
 tensor(4.9904, grad_fn=<DotBackward0>)


In [ ]:
# Attention Score inputs[1]
attn_scores_1 = []

for i in range(len(inputs)):
    key_vector = torch.matmul(inputs[i], Wk)  
    attn_score = torch.dot(query_for_journey, key_vector) 
    attn_scores_1.append(attn_score)

print("Attention scores inputs[1]:\n", attn_scores_1)

Attention scores inputs[1]:
 [tensor(2.8732, grad_fn=<DotBackward0>), tensor(4.9904, grad_fn=<DotBackward0>), tensor(4.9454, grad_fn=<DotBackward0>), tensor(2.8070, grad_fn=<DotBackward0>), tensor(2.7413, grad_fn=<DotBackward0>), tensor(3.4210, grad_fn=<DotBackward0>)]


In [13]:
# Attention weights inputs[1]
softmax_scores = torch.nn.functional.softmax(torch.tensor(attn_scores_1), dim=0)
print("Attention weights inputs[1]:\n", softmax_scores)

Attention weights inputs[1]:
 tensor([0.0481, 0.3996, 0.3820, 0.0450, 0.0422, 0.0832])


In [14]:
# Context vector inputs[1]
context_vector = torch.zeros(3)

for i in range(len(inputs)):
    value_vector = torch.matmul(inputs[i], Wv) 
    context_vector += softmax_scores[i] * value_vector  

print("Context vector inputs[1]:\n", context_vector)


Context vector inputs[1]:
 tensor([0.9860, 2.3239, 1.5093], grad_fn=<AddBackward0>)


In [15]:
# Weight Parameters for All Inputs
import torch.nn.functional as F

# Matrixes
W_Q = torch.randn(3, 3)  
W_K = torch.randn(3, 3)  
W_V = torch.randn(3, 3)  

Q = inputs @ W_Q  
K = inputs @ W_K  
V = inputs @ W_V  

# Attention scores
attention_scores = Q @ K.T 

# Attention weights
attention_weights = F.softmax(attention_scores, dim=1)

# Context vector
context_vectors = attention_weights @ V

print("Attention Scores:\n", attention_scores)
print("\nAttention Weights:\n", attention_weights)
print("\nContext Vectors:\n", context_vectors)


Attention Scores:
 tensor([[ 0.1635,  1.1155,  1.0418,  0.8855, -0.5797,  1.6267],
        [ 1.2884,  2.1836,  2.0885,  1.4387, -0.2142,  2.4290],
        [ 1.2990,  2.1314,  2.0412,  1.3901, -0.1591,  2.3316],
        [ 0.7533,  1.3436,  1.2815,  0.9019, -0.1994,  1.5454],
        [ 1.1244,  0.5905,  0.6147,  0.1229,  0.8776, -0.0793],
        [ 0.6938,  1.9217,  1.8086,  1.4200, -0.7379,  2.5677]])

Attention Weights:
 tensor([[0.0778, 0.2016, 0.1873, 0.1602, 0.0370, 0.3361],
        [0.0982, 0.2403, 0.2185, 0.1141, 0.0218, 0.3071],
        [0.1049, 0.2411, 0.2203, 0.1149, 0.0244, 0.2945],
        [0.1212, 0.2186, 0.2054, 0.1406, 0.0467, 0.2675],
        [0.2750, 0.1613, 0.1652, 0.1010, 0.2149, 0.0825],
        [0.0614, 0.2097, 0.1873, 0.1270, 0.0147, 0.4000]])

Context Vectors:
 tensor([[-0.5121,  0.8552,  0.5592],
        [-0.5482,  0.9291,  0.5807],
        [-0.5537,  0.9489,  0.5807],
        [-0.5537,  0.9813,  0.5669],
        [-0.6461,  1.4179,  0.5257],
        [-0.5000,  0.7