In [1]:
import numpy as np 

In [3]:
# Exercise 1
array1 = np.arange(0,10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# Exercise 2
list = [3.14, 2.17, 0, 1, 2]
array_int = np.array(list, dtype=int)
print(array_int)

[3 2 0 1 2]


In [6]:
# Exercise 3
array_3_3 = np.arange(1,10).reshape(3,3)
print(array_3_3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# Exercise 4
array_4_5 = np.random.rand(4, 5)
print(array_4_5)



[[0.83179612 0.63374231 0.71097535 0.62193423 0.80028569]
 [0.4484266  0.58646304 0.41569817 0.10140381 0.38047989]
 [0.59349219 0.18337042 0.1300168  0.68164178 0.97919759]
 [0.59592168 0.99214927 0.38406734 0.12007914 0.00173517]]


In [15]:
# Exercise 5
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
second_row = array[1,:]  
print(second_row)

[20 21 22 23 24]


In [16]:
# Exercise 6
array = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
reversed_array = array[::-1]  
print(reversed_array)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
# Exercise 7
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
# Exercise 8
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

sum_array = np.sum(array)
average_array = np.mean(array)

print(f"Sum: {sum_array}")
print(f"Average: {average_array}")

Sum: 45
Average: 4.5


In [19]:
# Exercise 9
array_4_5 = np.arange(1,21).reshape(4,5)
print(array_4_5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [21]:
# Exercise 10
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = array[array % 2 != 0]

print(f"Odd numbers: {odd_numbers}")

Odd numbers: [1 3 5 7 9]
