In [1]:
import numpy as np 

In [5]:
# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4, 5])
array_1d

array([1, 2, 3, 4, 5])

In [4]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Data Type:", array_1d.dtype)

Shape: (5,)
Size: 5
Data Type: int64


In [7]:
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Data Type:", array_2d.dtype)

Shape: (2, 3)
Size: 6
Data Type: int64


In [10]:
array1 = np.arange(1,6)
print(array1)
print("Shape:", array1.shape)
print("Size:", array1.size)
print("Data Type:", array1.dtype)

[1 2 3 4 5]
Shape: (5,)
Size: 5
Data Type: int64


In [11]:
array2 = np.arange(1,7).reshape(2,3)
print(array2)
print("Shape:", array2.shape)
print("Size:", array2.size)
print("Data Type:", array2.dtype)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int64


In [14]:
temp = np.array([0, 9, 7, 13, 14, 13, 15])
print(temp)

[ 0  9  7 13 14 13 15]


In [13]:
array_2 = np.arange(1,11).reshape(2,5)
print(array_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
image_array = np.random.randint(0, 256, size=(3, 3, 3), dtype=np.uint8)
print(image_array)

[[[106  26  16]
  [240  33 124]
  [194 119 126]]

 [[169 185 215]
  [255 111 255]
  [ 50 233 116]]

 [[  8 168 135]
  [ 14 110 138]
  [147 249 199]]]
